// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'alignas': 32,
//   'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'padlen': 1,
//   'precision': -1,
//   'quadrature_degree': -1,
//   'quadrature_rule': 'default',
//   'scalar_type': 'double',
//   'sycl_defines': True,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_element_3d50d284335ebc4b177a4e50d69ae334909fee4d(void);

ufc_finite_element* create_element_7fe73a8e5817bcc77c2cee5cf1074fd1ed41ed3e(void);

ufc_finite_element* create_element_0a5aeec74c03428a9a0cef4c980b0ad984414b71(void);

ufc_dofmap* create_dofmap_3d50d284335ebc4b177a4e50d69ae334909fee4d(void);

ufc_dofmap* create_dofmap_7fe73a8e5817bcc77c2cee5cf1074fd1ed41ed3e(void);

ufc_dofmap* create_dofmap_0a5aeec74c03428a9a0cef4c980b0ad984414b71(void);

ufc_coordinate_mapping* create_coordinate_mapping_789a3be9848adfb46412c6610644531fe182b431(void);

// Helper used to create coordinate map using name given to the
// UFL file.
// This helper is called in user c++ code.
//
ufc_coordinate_mapping* create_coordinate_map_poisson(void);

ufc_integral* create_integral_cell_otherwise_3bd9b7b20a517f650f9a1cba614b375d544dee36(void);

ufc_integral* create_integral_cell_otherwise_b2e4b1e5b423dd359e732fc7707ef351a42630b5(void);

ufc_form* create_form_3bd9b7b20a517f650f9a1cba614b375d544dee36(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_poisson_a(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_poisson_a(const char* fs_name);


ufc_form* create_form_b2e4b1e5b423dd359e732fc7707ef351a42630b5(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_poisson_L(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_poisson_L(const char* fs_name);


#ifdef __cplusplus
}
#endif
